 
  +-------------------------------------------------------------------------+
  |   This file has been generated by The Interactive Disassembler (IDA)    |
  |        Copyright (c) 2009 by Hex-Rays, <support@hex-rays.com>           |
  |                      License info: 22-156B-9052-13                      |
  |                              Licensed User                              |
  +-------------------------------------------------------------------------+
 
  Input MD5   : D00D731365DF672A4F1A62DA101DA4A3
  File Name   : E:\AVRSPI.hex
  Format      : Intel Hex Object Format
  Processor       : AVR      [ATmega8_L]
  Target assembler: AVR Assembler
  ===========================================================================
  Segment type: Pure code
 CSEG ; ROM
                .org 0
  =============== S U B R O U T I N E =======================================
 PM_RDY_0:                              ; CODE XREF: SPM_RDYj
                rjmp    __RESET         ; External Pin, Power-on Reset, Brown-out
  End of function SPM_RDY_0
  ---------------------------------------------------------------------------
                .org 1
                rjmp    SPM_RDY         ; Store Program Memory Ready
  ---------------------------------------------------------------------------
                .org 2
                rjmp    SPM_RDY         ; Store Program Memory Ready
  ---------------------------------------------------------------------------
                .org 3
                rjmp    SPM_RDY         ; Store Program Memory Ready
  ---------------------------------------------------------------------------
                .org 4
                rjmp    SPM_RDY         ; Store Program Memory Ready
  ---------------------------------------------------------------------------
                .org 5
                rjmp    SPM_RDY         ; Store Program Memory Ready
  ---------------------------------------------------------------------------
                .org 6
                rjmp    SPM_RDY         ; Store Program Memory Ready
  ---------------------------------------------------------------------------
                .org 7
                rjmp    SPM_RDY         ; Store Program Memory Ready
  ---------------------------------------------------------------------------
                .org 8
                rjmp    SPM_RDY         ; Store Program Memory Ready
  ---------------------------------------------------------------------------
                .org 9
                rjmp    SPM_RDY         ; Store Program Memory Ready
  ---------------------------------------------------------------------------
                .org 0xA
                rjmp    SPM_RDY         ; Store Program Memory Ready
  ---------------------------------------------------------------------------
                .org 0xB
                rjmp    SPM_RDY         ; Store Program Memory Ready
  ---------------------------------------------------------------------------
                .org 0xC
                rjmp    SPM_RDY         ; Store Program Memory Ready
  ---------------------------------------------------------------------------
                .org 0xD
                rjmp    SPM_RDY         ; Store Program Memory Ready
  ---------------------------------------------------------------------------
                .org 0xE
                rjmp    SPM_RDY         ; Store Program Memory Ready
  ---------------------------------------------------------------------------
                .org 0xF
                rjmp    SPM_RDY         ; Store Program Memory Ready
  ---------------------------------------------------------------------------
                .org 0x10
                rjmp    SPM_RDY         ; Store Program Memory Ready
  ---------------------------------------------------------------------------
                .org 0x11
                rjmp    SPM_RDY         ; Store Program Memory Ready
  ---------------------------------------------------------------------------
                .org 0x12
                rjmp    SPM_RDY         ; Store Program Memory Ready
  =============== S U B R O U T I N E =======================================
  External Pin, Power-on Reset, Brown-out
                ; public __RESET
 _RESET:                                ; CODE XREF: SPM_RDY_0j
  FUNCTION CHUNK AT ROM:002C SIZE 00000002 BYTES
                clr     r1
                out     SREG, r1
                ldi     r28, 0x5F ; '_'
                ldi     r29, 4
                out     SPH, r29
                out     SPL, r28
                rcall   sub_1C
                rjmp    loc_2C
  End of function __RESET
  [00000001 BYTES: COLLAPSED FUNCTION SPM_RDY. PRESS KEYPAD "+" TO EXPAND]
  =============== S U B R O U T I N E =======================================
 ub_1C:                                 ; CODE XREF: __RESET+6p
                in      r24, DDRB
                ori     r24, 0x2C
                out     DDRB, r24
                cbi     DDRB, DDB4
                sbi     SPCR, MSTR
                in      r24, SPCR
                ori     r24, 3
                out     SPCR, r24
                sbi     SPCR, SPE
                ldi     r24, -0x79 ; 'ç'
                out     SPDR, r24
 oc_27:                                 ; CODE XREF: sub_1C+Cj
                sbis    SPSR, SPIF
                rjmp    loc_27
                ldi     r24, 0
                ldi     r25, 0
                ret
  End of function sub_1C
  ---------------------------------------------------------------------------
  START OF FUNCTION CHUNK FOR __RESET
 oc_2C:                                 ; CODE XREF: __RESET+7j
                cli
 oc_2D:                                 ; CODE XREF: __RESET:loc_2Dj
                rjmp    loc_2D
  END OF FUNCTION CHUNK FOR __RESET
  ---------------------------------------------------------------------------
                .byte 1
  ===========================================================================
  Segment type: Pure data
 DSEG ; RAM
 0:             .byte 1
 1:             .byte 1
 2:             .byte 1
 3:             .byte 1
 4:             .byte 1
 5:             .byte 1
 6:             .byte 1
 7:             .byte 1
 8:             .byte 1
 9:             .byte 1
 10:            .byte 1
 11:            .byte 1
 12:            .byte 1
 13:            .byte 1
 14:            .byte 1
 15:            .byte 1
 16:            .byte 1
 17:            .byte 1
 18:            .byte 1
 19:            .byte 1
 20:            .byte 1
 21:            .byte 1
 22:            .byte 1
 23:            .byte 1
 24:            .byte 1
 25:            .byte 1
 26:            .byte 1
 27:            .byte 1
 28:            .byte 1
 29:            .byte 1
 30:            .byte 1
 31:            .byte 1
 WBR:           .byte 1                 ; Two-wire Serial Interface Bit Rate Register
 WSR:           .byte 1                 ; TWI Status Register
 WAR:           .byte 1                 ; TWI (Slave) Address Register
 WDR:           .byte 1                 ; TWI Data Register
 DCL:           .byte 1                 ; ADC Data Register Low (ADLAR = 0)
 DCH:           .byte 1                 ; ADC Data Register High (ADLAR = 0)
 DCSRA:         .byte 1                 ; ADC Control and Status Register A
 DMUX:          .byte 1                 ; ADC Multiplexer Selection Register
 CSR:           .byte 1                 ; Analog Comparator Control and Status Register
 BRRL:          .byte 1                 ; USART Baud Rate Register Low
 CSRB:          .byte 1                 ; USART Control and Status Register B
 CSRA:          .byte 1                 ; USART Control and Status Register A
 DR:            .byte 1                 ; USART I/O Data Register
 PCR:           .byte 1                 ; SPI Control Register
 PSR:           .byte 1                 ; SPI Status Register
 PDR:           .byte 1                 ; SPI Data Register
 IND:           .byte 1                 ; Port D Input Pins Address
 DRD:           .byte 1                 ; Port D Data Direction Register
 ORTD:          .byte 1                 ; Port D Data Register
 INC:           .byte 1                 ; Port C Input Pins Address
 DRC:           .byte 1                 ; Port C Data Direction Register
 ORTC:          .byte 1                 ; Port C Data Register
 INB:           .byte 1                 ; Port B Input Pins Address
 DRB:           .byte 1                 ; Port B Data Direction Register
 ORTB:          .byte 1                 ; Port B Data Register
 ESERVED0019:   .byte 1                 ; RESERVED
 ESERVED001A:   .byte 1                 ; RESERVED
 ESERVED001B:   .byte 1                 ; RESERVED
 ECR:           .byte 1                 ; EEPROM Control Register
 EDR:           .byte 1                 ; EEPROM Data Register
 EARL:          .byte 1                 ; EEPROM Address Register Low
 EARH:          .byte 1                 ; EEPROM Address Register High
 CSRC:          .byte 1                 ; USART Control and Status Register (page 148)
 DTCR:          .byte 1                 ; Watchdog Timer Control Register
 SSR:           .byte 1                 ; Asynchronous Status Register
 CR2:           .byte 1                 ; Output Compare Register
 CNT2:          .byte 1                 ; Timer/Counter Register
 CCR2:          .byte 1                 ; Timer/Counter Control Register
 CR1L:          .byte 1                 ; Input Capture Register 1 Low
 CR1H:          .byte 1                 ; Input Capture Register 1 High
 CR1BL:         .byte 1                 ; Output Compare Register 1 B Low
 CR1BH:         .byte 1                 ; Output Compare Register 1 B High
 CR1AL:         .byte 1                 ; Output Compare Register 1 A Low
 CR1AH:         .byte 1                 ; Output Compare Register 1 A High
 CNT1L:         .byte 1                 ; Timer/Counter 1 Low
 CNT1H:         .byte 1                 ; Timer/Counter 1 High
 CCR1B:         .byte 1                 ; Timer/Counter 1 Control Register B
 CCR1A:         .byte 1                 ; Timer/Counter 1 Control Register A
 FIOR:          .byte 1                 ; Special Function IO Register
 SCCAL:         .byte 1                 ; Oscillator Calibration Register
 CNT0:          .byte 1                 ; Timer/Counter Register
 CCR0:          .byte 1                 ; Timer/Counter Control Register
 CUCSR:         .byte 1                 ; MCU Control and Status Register
 CUCR:          .byte 1                 ; MCU Control Register
 WCR:           .byte 1                 ; TWI Control Register
 PMCR:          .byte 1                 ; Store Program Memory Control Register
 IFR:           .byte 1                 ; Timer/Counter Interrupt Flag Register
 IMSK:          .byte 1                 ; Timer/Counter Interrupt Mask Register
 IFR:           .byte 1                 ; General Interrupt Flag Register
 ICR:           .byte 1                 ; General Interrupt Control Register
 ESERVED003C:   .byte 1                 ; RESERVED
 PL:            .byte 1                 ; Stack Pointer Low
 PH:            .byte 1                 ; Stack Pointer High
 REG:           .byte 1                 ; Status Register
                .byte 1
                .byte 1
                .byte 1
                .exit ;

