
 +-------------------------------------------------------------------------+
 |   This file has been generated by The Interactive Disassembler (IDA)    |
 |        Copyright (c) 2009 by Hex-Rays, <support@hex-rays.com>           |
 |                      License info: 22-156B-9052-13                      |
 |                              Licensed User                              |
 +-------------------------------------------------------------------------+

 Input MD5   : C7623A6914D6DB3EB29AFEE0CFD27AB7
 File Name   : E:\AVRSPI.hex
 Format      : Intel Hex Object Format
 Processor       : AVR      [ATmega8_L]
 Target assembler: AVR Assembler
 ===========================================================================
 Segment type: Pure code
CSEG ; ROM
 [00000001 BYTES: COLLAPSED FUNCTION SPM_RDY_0. PRESS KEYPAD "+" TO EXPAND]
 ---------------------------------------------------------------------------
               .org 1
               rjmp    SPM_RDY         ; Store Program Memory Ready
 ---------------------------------------------------------------------------
               .org 2
               rjmp    SPM_RDY         ; Store Program Memory Ready
 ---------------------------------------------------------------------------
               .org 3
               rjmp    SPM_RDY         ; Store Program Memory Ready
 ---------------------------------------------------------------------------
               .org 4
               rjmp    SPM_RDY         ; Store Program Memory Ready
 ---------------------------------------------------------------------------
               .org 5
               rjmp    SPM_RDY         ; Store Program Memory Ready
 ---------------------------------------------------------------------------
               .org 6
               rjmp    SPM_RDY         ; Store Program Memory Ready
 ---------------------------------------------------------------------------
               .org 7
               rjmp    SPM_RDY         ; Store Program Memory Ready
 ---------------------------------------------------------------------------
               .org 8
               rjmp    SPM_RDY         ; Store Program Memory Ready
 ---------------------------------------------------------------------------
               .org 9
               rjmp    SPM_RDY         ; Store Program Memory Ready
 ---------------------------------------------------------------------------
               .org 0xA
               rjmp    SPM_RDY         ; Store Program Memory Ready
 ---------------------------------------------------------------------------
               .org 0xB
               rjmp    SPM_RDY         ; Store Program Memory Ready
 ---------------------------------------------------------------------------
               .org 0xC
               rjmp    SPM_RDY         ; Store Program Memory Ready
 ---------------------------------------------------------------------------
               .org 0xD
               rjmp    SPM_RDY         ; Store Program Memory Ready
 ---------------------------------------------------------------------------
               .org 0xE
               rjmp    SPM_RDY         ; Store Program Memory Ready
 ---------------------------------------------------------------------------
               .org 0xF
               rjmp    SPM_RDY         ; Store Program Memory Ready
 ---------------------------------------------------------------------------
               .org 0x10
               rjmp    SPM_RDY         ; Store Program Memory Ready
 ---------------------------------------------------------------------------
               .org 0x11
               rjmp    SPM_RDY         ; Store Program Memory Ready
 ---------------------------------------------------------------------------
               .org 0x12
               rjmp    SPM_RDY         ; Store Program Memory Ready
 =============== S U B R O U T I N E =======================================
 External Pin, Power-on Reset, Brown-out
               ; public __RESET
_RESET:                                ; CODE XREF: SPM_RDY_0j
 FUNCTION CHUNK AT ROM:002B SIZE 00000002 BYTES
               clr     r1
               out     SREG, r1
               ldi     r28, 0x5F ; '_'
               ldi     r29, 4
               out     SPH, r29
               out     SPL, r28
               rcall   sub_1C
               rjmp    loc_2B
 End of function __RESET
 [00000001 BYTES: COLLAPSED FUNCTION SPM_RDY. PRESS KEYPAD "+" TO EXPAND]
 =============== S U B R O U T I N E =======================================
ub_1C:                                 ; CODE XREF: __RESET+6p
               in      r24, DDRB
               ori     r24, 0x2C
               out     DDRB, r24
               cbi     DDRB, DDB4
               sbi     SPCR, MSTR
               in      r24, SPCR
               ori     r24, 3
               out     SPCR, r24
               sbi     SPCR, SPE
               out     SPDR, r1
oc_26:                                 ; CODE XREF: sub_1C+Bj
               sbis    SPSR, SPIF
               rjmp    loc_26
               ldi     r24, 0
               ldi     r25, 0
               ret
 End of function sub_1C
 ---------------------------------------------------------------------------
 START OF FUNCTION CHUNK FOR __RESET
oc_2B:                                 ; CODE XREF: __RESET+7j
               cli
oc_2C:                                 ; CODE XREF: __RESET:loc_2Cj
               rjmp    loc_2C
 END OF FUNCTION CHUNK FOR __RESET
 ---------------------------------------------------------------------------

 ; ===========================================================================

 ; Segment type: Pure data
 .DSEG ; RAM
 r0:             .byte 1
 r1:             .byte 1
 r2:             .byte 1
 r3:             .byte 1
 r4:             .byte 1
 r5:             .byte 1
 r6:             .byte 1
 r7:             .byte 1
 r8:             .byte 1
 r9:             .byte 1
 r10:            .byte 1
 r11:            .byte 1
 r12:            .byte 1
 r13:            .byte 1
 r14:            .byte 1
 r15:            .byte 1
 r16:            .byte 1
 r17:            .byte 1
 r18:            .byte 1
 r19:            .byte 1
 r20:            .byte 1
 r21:            .byte 1
 r22:            .byte 1
 r23:            .byte 1
 r24:            .byte 1
 r25:            .byte 1
 r26:            .byte 1
 r27:            .byte 1
 r28:            .byte 1
 r29:            .byte 1
 r30:            .byte 1
 r31:            .byte 1
 TWBR:           .byte 1                 ; Two-wire Serial Interface Bit Rate Register
 TWSR:           .byte 1                 ; TWI Status Register
 TWAR:           .byte 1                 ; TWI (Slave) Address Register
 TWDR:           .byte 1                 ; TWI Data Register
 ADCL:           .byte 1                 ; ADC Data Register Low (ADLAR = 0)
 ADCH:           .byte 1                 ; ADC Data Register High (ADLAR = 0)
 ADCSRA:         .byte 1                 ; ADC Control and Status Register A
 ADMUX:          .byte 1                 ; ADC Multiplexer Selection Register
 ACSR:           .byte 1                 ; Analog Comparator Control and Status Register
 UBRRL:          .byte 1                 ; USART Baud Rate Register Low
 UCSRB:          .byte 1                 ; USART Control and Status Register B
 UCSRA:          .byte 1                 ; USART Control and Status Register A
 UDR:            .byte 1                 ; USART I/O Data Register
 SPCR:           .byte 1                 ; SPI Control Register
 SPSR:           .byte 1                 ; SPI Status Register
 SPDR:           .byte 1                 ; SPI Data Register
 PIND:           .byte 1                 ; Port D Input Pins Address
 DDRD:           .byte 1                 ; Port D Data Direction Register
 PORTD:          .byte 1                 ; Port D Data Register
 PINC:           .byte 1                 ; Port C Input Pins Address
 DDRC:           .byte 1                 ; Port C Data Direction Register
 PORTC:          .byte 1                 ; Port C Data Register
 PINB:           .byte 1                 ; Port B Input Pins Address
 DDRB:           .byte 1                 ; Port B Data Direction Register
 PORTB:          .byte 1                 ; Port B Data Register
 RESERVED0019:   .byte 1                 ; RESERVED
 RESERVED001A:   .byte 1                 ; RESERVED
 RESERVED001B:   .byte 1                 ; RESERVED
 EECR:           .byte 1                 ; EEPROM Control Register
 EEDR:           .byte 1                 ; EEPROM Data Register
 EEARL:          .byte 1                 ; EEPROM Address Register Low
 EEARH:          .byte 1                 ; EEPROM Address Register High
 UCSRC:          .byte 1                 ; USART Control and Status Register (page 148)
 WDTCR:          .byte 1                 ; Watchdog Timer Control Register
 ASSR:           .byte 1                 ; Asynchronous Status Register
 OCR2:           .byte 1                 ; Output Compare Register
 TCNT2:          .byte 1                 ; Timer/Counter Register
 TCCR2:          .byte 1                 ; Timer/Counter Control Register
 ICR1L:          .byte 1                 ; Input Capture Register 1 Low
 ICR1H:          .byte 1                 ; Input Capture Register 1 High
 OCR1BL:         .byte 1                 ; Output Compare Register 1 B Low
 OCR1BH:         .byte 1                 ; Output Compare Register 1 B High
 OCR1AL:         .byte 1                 ; Output Compare Register 1 A Low
 OCR1AH:         .byte 1                 ; Output Compare Register 1 A High
 TCNT1L:         .byte 1                 ; Timer/Counter 1 Low
 TCNT1H:         .byte 1                 ; Timer/Counter 1 High
 TCCR1B:         .byte 1                 ; Timer/Counter 1 Control Register B
 TCCR1A:         .byte 1                 ; Timer/Counter 1 Control Register A
 SFIOR:          .byte 1                 ; Special Function IO Register
 OSCCAL:         .byte 1                 ; Oscillator Calibration Register
 TCNT0:          .byte 1                 ; Timer/Counter Register
 TCCR0:          .byte 1                 ; Timer/Counter Control Register
 MCUCSR:         .byte 1                 ; MCU Control and Status Register
 MCUCR:          .byte 1                 ; MCU Control Register
 TWCR:           .byte 1                 ; TWI Control Register
 SPMCR:          .byte 1                 ; Store Program Memory Control Register
 TIFR:           .byte 1                 ; Timer/Counter Interrupt Flag Register
 TIMSK:          .byte 1                 ; Timer/Counter Interrupt Mask Register
 GIFR:           .byte 1                 ; General Interrupt Flag Register
 GICR:           .byte 1                 ; General Interrupt Control Register
 RESERVED003C:   .byte 1                 ; RESERVED
 SPL:            .byte 1                 ; Stack Pointer Low
 SPH:            .byte 1                 ; Stack Pointer High
 SREG:           .byte 1                 ; Status Register
                 .byte 1
                 .byte 1

                .exit ;
